### ISSUE TITLE
Create-A-Sim no longer starts transferring to East Jerome once the User presses Accept.

### ISSUE THREAD

**Issue by Blayer98** [Afr0/Project-Dollhouse#118]
Pretty much self explanatory...

Not sure why it's not doing it... :/

**Comment by ZackCDLVI** [comment]
Does it crash right away? I've had it crash after I finished CAS.

**Comment by Blayer98** [comment]
Nope, doesn't Crash for me, It just stays on there until I exit the game.

**Comment by Blayer98** [comment]
This has been fixed, I'm closing the issue.
