### ISSUE TITLE
Bug - W7x64

### ISSUE THREAD

**Issue by Fanobii** [Afr0/Project-Dollhouse#131]
If I'm allowed to post bugs here, even though I shouldn't be playing the game, out of curiosity I tried playing today.
Just 2 things before I continue:
1. I do not plan to play the game online, you can ban me if you wish.
2. I don't mind if you ban me from the GitHub / whatever

Alright.  So today I opened the PD Patcher to find a small update.  After updating, it launched the game with this error:

![screen1](https://cloud.githubusercontent.com/assets/8849611/6252612/84d464fc-b793-11e4-85a7-02210cab4d3f.png)

It is a Client error (not a patcher error) as visible by the last line ("at TSOClient.Program...").  I tried updating again and got the same error.  Any idea on when a fix will be issued? Just curious.  I wonder if anyone else gets this?
I assume it is not a hardware error but a software error as there is a method missing.

Again, apologies if I'm not allowed to say anything here, I just thought I'd let you know.
EDIT: Not trying to tell you what to do or anything, just asking if a fix will be issued.  Not rushing you :smile:

**Comment by Afr0** [comment]
Delete TSO.World.dll

**Comment by Fanobii** [comment]
The hotfix works fine.  It's just that, in the GitHub repo/latest code, it appears to be there:
![screen2](https://cloud.githubusercontent.com/assets/8849611/6253471/90e317e2-b799-11e4-95d0-a3a7bbac0917.png)

**Comment by RHY3756547** [comment]
You don't even know what you're talking about, stop. It's not a hotfix, it's accessing an old binary (new one is .exe due to a build misconfiguration)

**Comment by Fanobii** [comment]
Ok, fine, but either way, it's a fix.
