### ISSUE TITLE
Include a default server configuration

### ISSUE THREAD

**Issue by descention** [Afr0/Project-Dollhouse#132]
Either include a file in the project for ServerConfig.ini with default parameters or have the catch be a FileNotFoundException and load the global variables with default values.

Edit: This is in reference to: https://github.com/Afr0/Project-Dollhouse/blob/master/TSO%20CityServer/TSO%20CityServer/ConfigurationManager.cs#L50

**Comment by Afr0** [comment]
Pretty sure there should be a SampleServerConfig.ini (or similar), but I'm not sure it's in the project?

Date: Tue, 24 Mar 2015 13:19:46 -0700

**Comment by descention** [comment]
You are correct. It's not found when doing a search on github. Hopefully this issue will help future searches.

**Comment by Afr0** [comment]
By the way, we need more developers on this thing, so please feel free to fix issues!

**Comment by Afr0** [comment]
I included it in the project!
