### ISSUE TITLE
Crashing on Launch? Windows 8.1

### ISSUE THREAD

**Issue by DukeLukum** [Afr0/Project-Dollhouse#139]
I'm getting an error that pops up after the update utility comes up, The code says:
![tso problem](https://cloud.githubusercontent.com/assets/12452288/7643851/2a536844-fa95-11e4-9c85-e991b8ffd25b.png)
My System:
![my system](https://cloud.githubusercontent.com/assets/12452288/7643868/71021286-fa95-11e4-8c30-897b42faef67.png)
I would appreciate some help towards this, Thank you.

**Comment by Afr0** [comment]
Install XNA Redist 3.1. Kinda strange though, it shouldn't be neccessary any more. If it still complains, install Monogame.

Date: Thu, 14 May 2015 16:01:27 -0700

**Comment by ZackCDLVI** [comment]
> Install XNA Redist 3.1. Kinda strange though, it shouldn't be neccessary any more. If it still complains, install Monogame. 

It's isn't. MonoGame's assemsibles should come with the installation or at least in all new patches. Try running in compatibility mode: Windows 7, DukeLukum.

**Comment by RHY3756547** [comment]
You might be using an old version. The latest is compiled using Monogame, and the XNA version is 4.0. You shouldn't need to download anything for the latest version (monogame is standalone i think), but I haven't verified this.

**Comment by DukeLukum** [comment]
I've downgraded my computer to Windows 8 from 8.1 hoping it will fix the problem, When I tried installing Xna 3.1 it came up with some errors after installing it, Not sure what it was, If I get them again I will post a picture.

**Comment by RHY3756547** [comment]
If anything, you would only need to install the redistributable, not the whole XNA framework.

**Comment by DukeLukum** [comment]
I've installed the Red version off of Microsofts page, I just need to re-install TSO and the PD Installer and test

**Comment by DukeLukum** [comment]
I'm getting this error with BASS.NET, Is this normal?
![bass net error](https://cloud.githubusercontent.com/assets/12452288/7653175/977d6d0e-fb0b-11e4-80ee-603098a6bfb4.png)

**Comment by Afr0** [comment]
I'm not sure it's "normal", but you shouldn't need those files anyway.

**Comment by DukeLukum** [comment]
Ok, I've installed TSO fine, I installed the Dollhouse Project fine, Still getting an error message (Running in compatibility mode for Windows 7) but the message is shorter, Must be good, Right?
![xna error](https://cloud.githubusercontent.com/assets/12452288/7653267/4b695e54-fb0c-11e4-8f3a-519fabe1d2df.png)

**Comment by DukeLukum** [comment]
What do I download from MonoGame? @Afr0

**Comment by Afr0** [comment]
Delete tso.world.dll and you should be good.

**Comment by DukeLukum** [comment]
It started loading, And then I got this.... It seems like it doesn't want me to play it.....
![error](https://cloud.githubusercontent.com/assets/12452288/7653519/2f4b4a96-fb0e-11e4-828d-d40d1cb569f2.png)

**Comment by Afr0** [comment]
You need to install OpenAL....

**Comment by DukeLukum** [comment]
Have you got a download link for that please?

**Comment by ZackCDLVI** [comment]
http://www.openal.org/creative-installers/oalinst.zip

**Comment by DukeLukum** [comment]
I've got it now, Thank you everyone for all your help :)
